# Generated by Django 3.1.2 on 2021-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210126_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.TextField(default=None, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=None, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.TextField(default=None, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=None, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=None, verbose_name='Дата выпуска'),
        ),
    ]
