# Generated by Django 3.1.2 on 2021-01-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20210126_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.TextField(null=True, verbose_name='Изображение'),
        ),
    ]
