# Generated by Django 3.1.2 on 2021-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20210126_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.TextField(default=None),
        ),
    ]
